### ISSUE TITLE
SRAM with 2 banks is messed up

### ISSUE THREAD

**Issue by mattfel1** [stanford-ppl/spatial#12]
I think this is because the rule for `FixMod(_, Const(r))` is:
```
    case (_, Const(r)) if r.isPow2 && r > 0 =>
      val i = INT[F].v + Number.log2(r).toInt - 1
      if (i <= 0) a.from(0)
      else a.bits(i::0).asUnchecked[Fix[S,I,F]]
```
If r is 2, then it will take the (i <= 0) branch but it shouldn't.  I made this fix locally for now and will push it if this confirmed to be incorrect

**Comment by dkoeplin** [comment]
Looks correct. Did we confirm this fixed the addressing issue with 2 banks yet?

**Comment by mattfel1** [comment]
Fixed this and a few other rewrite rules a while back
