### ISSUE TITLE
isInnerPipe Considers Scheduling (AKA Fully Unrolled Loop = Sched.Sequential)?

### ISSUE THREAD

**Issue by mattfel1** [stanford-ppl/spatial#14]
I have a fully unrolled vs partially unrolled inner pipe.  In the case of fully unrolled, it is `Sched.Sequential` and in the case of partially unrolled, it is `Sched.Pipe`.  Neither of these really seem bad since it is the Initiation Interval that controls how an innerpipe executes, but for `requireParallelPortAccess`, it checks `lca.isInnerPipe`.  I would expect it to return true regardless of the schedule, but this function has ` && isPipeline` included.  It also includes `toCtrl.isLoop`, which is false if the loop will fully unroll.  Shouldn't an inner UnitPipe still return true for `isInnerPipe`

I think one of these is wrong.  Either the fully unrolled inner pipe should have `Sched.Pipe` or the `isInnerPipe` should not look at the schedule.

OR is a `Sched.Sequential` different from having an II = body latency and I need to make changes to the inner controller template?

**Comment by dkoeplin** [comment]
Now refactored according to our discussion about helper functions
