### ISSUE TITLE
RegRead Outside Accel Being Used Inside Accel

### ISSUE THREAD

**Issue by mattfel1** [stanford-ppl/spatial#16]
Seeing this in FoldSimple2

**Comment by mattfel1** [comment]
This looks fixed

**Comment by mattfel1** [comment]
Wait nevermind.  I still see it in Read\*SV2D and SmallTensorLoad and Tensor\*D

**Comment by dkoeplin** [comment]
Closing this issue again - looks like we've fully fixed it now. Added a sanity check to catch this case at end of compilation just in case.
