### ISSUE TITLE
Fork Inside ForkJoin With Pipe Insertion (Reprise)

### ISSUE THREAD

**Issue by mattfel1** [stanford-ppl/spatial#166]
There should really be a fix for this kind of thing since its not obvious to the average user and it always takes a few minutes to trace down the issue for me when I'm debugging their waveform.  The pipe inserter injects the sramread/regwrite in front of the switch as its own unit pipe.  The parallel schedule allows the switch to "resolve" before the unit pipe is done.
```
Parallel{
  val cond = // sram read
  if (cond) { // Outer switch
    ...
  }
  if (cond) { // Outer switch // Second one so it matches with the image below
    ...
  }
}
```
becomes
![image](https://user-images.githubusercontent.com/8563453/49317432-4f300e80-f4a9-11e8-9d78-5c8e75b4b54a.png)

**Comment by mattfel1** [comment]
Fixed this in what I thought was the most reasonable way.  Generally people tend to write if blocks inside of their Parallel and they actually intend for the cond resolution to happen before the switch runs.  (also happens with setting up dram transfer bounds).  The pipe inserter used to step through the stms of an outer controller and mark the stage that each one belongs in.  Then it would go through and transform each stage, inserting the escaping regs if needed.  I added a step inbetween here where it steps through each of the stages and binds one stage to its subsequent stage if the escaping values are used there, and wraps the two together in a pipe.

What I'm not sure about is if there is a condition used by multiple stages in the parallel.  Will the transient analysis have already given each stage its own read of the condition, and will they be placed in the IR in the order that makes this new check work?

**Comment by dkoeplin** [comment]
Your fix makes sense, but technically the original program is incorrect. Parallel means do everything in parallel, so including things that had data dependencies is an incorrect usage. 

The correct implementation should be (and perhaps we can automate it to this): 
```
// Should get a Pipe { } and a register
val cond = // sram read

Parallel{  
  if (cond) { // Outer switch
    ...
  }
  if (cond) { // Outer switch // Second one so it matches with the image below
    ...
  }
}
```

**Comment by mattfel1** [comment]
The thing that makes it confusing is that people usually express it this way:

```
Parallel{
  if (a == b && c == d) { stuff }
}
```
So it's not immediately obvious, even if it looks the same in the IR.  Pushing the pipe-inserted primitives up and out of the Parallel works too.  It was much easier though to take advantage of pipe insertion and edit it this way.
