### ISSUE TITLE
Document emptiness dependencies

### ISSUE THREAD

**Issue by dkoeplin** [stanford-ppl/spatial#186]
We may not have these documented anywhere yet, should make it clear that there are dependencies on pkg-config, libisl-dev, and libgmp3-dev to get emptiness to compile for the first time.

```
sudo apt-get install pkg-config
sudo apt-get install libisl-dev
sudo apt-get install libgmp3-dev
```

**Comment by mattfel1** [comment]
Added pkg-config and libgmp3-dev as prereqs on the website
