### ISSUE TITLE
RetimingTransformer Created a Negative Delay when Analyzing RegFiles

### ISSUE THREAD

**Issue by kelayamatoz** [stanford-ppl/spatial#189]
The app is located at: https://github.com/kelayamatoz/spatialNLP/tree/retiming_transformer_bug
Spatial commit is at issue140_dse: f8d3a909e227610a7c92b136db5243469f8c55c8

cmd line to trigger this issue:  sbt "runMain TokenizerSynthMid10VCS --synth --fpga vcs --instrumentation --vv"  && cd gen/TokenizerSynthMid10VCS && make

**Comment by mattfel1** [comment]
Tried on current issue140_dse branch with dbPrintln method stripped and added .buffer flag to a few memories that it complained about and it seems to work for me.
