### ISSUE TITLE
instanceIndexOf Nonexistent

### ISSUE THREAD

**Issue by mattfel1** [stanford-ppl/spatial#20]
I found a case where instanceIndexOf(reader) gives the error:
 java.util.NoSuchElementException: None.get

In this case, there is only one duplicate of the bram.   I fixed this temporarily just by setting instanceIndexOf(reader) to 0 if there is only one duplicate.  

I know there are other cases where there is only one duplicate and instanceIndexOf works just fine though.  You can reproduce this error by running GDA on plasticine branch (commit 2e02ac61757af7 on forge).

**Comment by dkoeplin** [comment]
Structure of memory analysis has changed significantly. Future problems with instanceIndices / memory analysis should be tracked with a new issue.
