### ISSUE TITLE
sbt test parsing underscores

### ISSUE THREAD

**Issue by mattfel1** [stanford-ppl/spatial#21]
For example, the app called `Scan_fillfifo` becomes an app called `fillfifo` in directory `Scan`.

**Comment by dkoeplin** [comment]
This is actually desired behavior to have multiple subclasses of the same app (e.g. different numeric types but same application, etc.)

**Comment by mattfel1** [comment]
That makes sense, it seems like there are some apps that should be renamed in that case, like MemCopySRAM2D_2.  For the synth regression I was taking the last directory and using that as the app name, so some really weird names started appearing
