### ISSUE TITLE
Dense Transfer Controllers becoming Sequential

### ISSUE THREAD

**Issue by mattfel1** [stanford-ppl/spatial#22]
Just noticed this is happening, where the user schedule is Streaming (correct) but the schedule gets set to sequential:

```
              x193 = UnitPipe(Set(b173),Block(Const((): class scala.runtime.BoxedUnit))) {
               - class spatial.data.ControlSchedule: ControlSchedule(Sequenced)
               - class spatial.data.UserScheduleDirective: UserScheduleDirective(Streaming)
```

Should the controlSchedule flow have a rule to choose the Streaming schedule if it is defined at the end of the flow, like this?  

```
if (s.isOuterControl && s.getUserSchedule.isDefined && s.getUserSchedule.get == Streaming) s.rawSchedule = Streaming
```

It seems like the unrolling transformer is losing some information because it doesn't follow this flow, but if retime is turned on then the flow is called there and it is correct by the last IR.  Maybe this is because of the mutate transformer and the order that it copies metadata?  I also see this happening with a Sequential.Foreach becoming a Pipeline by the last IR.  I'm using FIFOLoadSRAMStore for debugging this.

**Comment by dkoeplin** [comment]
Fixed in 4aa747881725d48a53e73f2b6529a46227d793c1
