### ISSUE TITLE
Fuse Multiply Add Accumulator

### ISSUE THREAD

**Issue by yaqiz01** [stanford-ppl/spatial#237]
ReduceSpecialization Test fail due to a bug fix in CanFuseFMA setter.
In AccumAnalyzer need to match on the multiply add with mux structure instead of FMA directly because previously FMA was incorrectly fused.

**Comment by mattfel1** [comment]
Fixed in c7a50b18.  RewriteAnalyzer now looks for either mul.consumers.size == 1 OR mul.consumers.size == 2 and everything fits into the reg = `mux( _, a * b, reg + a * b)` pattern
