### ISSUE TITLE
Banking Analysis Infers Fewer Banks under the Context of Metaprogramming a Reduce Tree

### ISSUE THREAD

**Issue by kelayamatoz** [stanford-ppl/spatial#244]
For example, if I have a reduce tree that looks like: 
```scala
Foreach (N by K) { i => 
  List.tabulate(K) { ii => 
    val a = w(i + ii)
    val b = v(i + ii)
    val re = a * b
    re
  }.sumTree
  ...
}
```

Banking will infer K-1 banks instead of K banks. The reason is that the first bank, i + 0, will be rewritten by argon as i. As a result, only the next K-1 banks will be inferred.

**Comment by mattfel1** [comment]
Fixed.  In the case I was looking at, it thought that lane 0 and the other lanes happen at different points in time and forgot to consider that the inner controller is looped with II = 1, so there is actually a bank conflict.  I think it had something to do with the case (not shown here) having an inner switch case as its immediate parent.  I added a test (MetaprogrammedConflict) which should expose this but it only exposed it when I put a dummy switch case around the access.  Either way, this is fixed now.  Accesses require concurrent port access even if their retiming separates them, if their innermost loop-able controller is looped (and has II = 1 but for now I'm just treating it the same regardless of II so we don't have to do an extra pass just for this)
