### ISSUE TITLE
topWritersOf() and writersOf() are identical for a DblBuf

### ISSUE THREAD

**Issue by mattfel1** [stanford-ppl/spatial#25]
I have a BRAM that is the accumulator in a Fold.  Both the writersOf and the topWritersOf this BRAM are the same, even though the topWritersOf should point to the outer metapipe.

See MatMult_outer.scala on branch maxj, commit 5d8f51aea519c.  The problem BRAM is BRAM3628_1, who has pipe3733_done instead of metapipe3735_done as the topWriterOf

**Comment by dkoeplin** [comment]
Refactored to topControllerOf for readers and writers to buffers. Future issues should use a new issue
