### ISSUE TITLE
FloatingPoint Class Doesn't Have toSeq Method

### ISSUE THREAD

**Issue by kelayamatoz** [stanford-ppl/spatial#255]
Our chiselgen runs toSeq over a Wire object. However, fringe.templates.math.FloatingPoint class doesn't have a toSeq method. I'm testing a patch that adds a toSeq method to the FloatingPoint class.

**Comment by kelayamatoz** [comment]
Added patch to branch issue255_fltpt2seq: 7ff1bd9d11e4240df2cdf442f50aed9c07f2570b
@mattfel1 Should I merge it into develop or wait for the admin to merge? 
Test app attached:  [HelloFloat.scala.zip](https://github.com/stanford-ppl/spatial/files/3332144/HelloFloat.scala.zip)

**Comment by mattfel1** [comment]
This one line looks safe enough so you can merge. Are you working on floating point implementations for everything now?

**Comment by kelayamatoz** [comment]
I had an app that required high-precision non-linear function implementations for FPGA and that's why I was hitting this issue. I'm not implementing floating point for everything.

By looking at the fringe templates, it seems that the floating point (32 bit) implementations are there already. Is there still anything missing?

**Comment by mattfel1** [comment]
Anything floating point is use-at-your-own risk right now.  Last I checked, only addition, subtraction, and multiplication are semi-trustworthy

**Comment by kelayamatoz** [comment]
Got it. I will see how far I can get. Basically + - * and format conversion from 32bit Int is pretty much all I need.
