### ISSUE TITLE
Allow Time Multiplexed Multiple Writers to BRAM

### ISSUE THREAD

**Issue by mattfel1** [stanford-ppl/spatial#26]
I have a version of GEMM that loads the previous value of a tile and then accumulates on top of that.  Spatial or delite is seeing this as a memory with multiple writers and quitting.  The parent pipes of the two writers are different stages of the same outer pipe, so I would like to have this allowed and just the wdata stream based on the parent pipe's en.  This will work for sequential pipes.

Not yet sure if I will need more info exposed when there are multiple writers inside of a metapipe.

GEMM on spatial branch maxj commit 760a1948a651 will show this error.

**Comment by dkoeplin** [comment]
Fully supported after commit [dc668db](https://github.com/stanford-ppl/spatial/commit/dc668db05c5b014fb736e9a50959ef719a671c3f)
