### ISSUE TITLE
many erros  when do bin/spatial HelloSpatial --sim

### ISSUE THREAD

**Issue by lznnnnn1998** [stanford-ppl/spatial#283]
please help....
spatial-master$ bin/spatial HelloSpatial --sim
[info] Loading global plugins from /home/cristinazn/.sbt/1.0/plugins
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /home/cristinazn/Downloads/tslab/spatial-master/project
[info] Loading settings from build.sbt ...
[info] Set current project to spatial (in build file:/home/cristinazn/Downloads/tslab/spatial-master/)
[info] Set current project to apps (in build file:/home/cristinazn/Downloads/tslab/spatial-master/)
[info] Updating forge...
[info] Updating models...
[info] Updating poly...
[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* org.scala-lang.modules:scala-xml_2.12:1.1.0 is selected over 1.0.6
[warn] 	    +- edu.stanford.cs.dawn:models_2.12:1.1-SNAPSHOT      (depends on 1.0.6)
[warn] 	    +- edu.stanford.cs.dawn:utils_2.12:1.1-SNAPSHOT       (depends on 1.0.6)
[warn] 	    +- org.scala-lang:scala-compiler:2.12.7               (depends on 1.0.6)
[warn] 	    +- org.scalatest:scalatest_2.12:3.0.5                 (depends on 1.0.6)
[warn] Run 'evicted' to see detailed eviction warnings
[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* org.scala-lang.modules:scala-xml_2.12:1.1.0 is selected over 1.0.6
[warn] 	    +- edu.stanford.cs.dawn:emul_2.12:1.1-SNAPSHOT        (depends on 1.1.0)
[warn] 	    +- edu.stanford.cs.dawn:utils_2.12:1.1-SNAPSHOT       (depends on 1.0.6)
[warn] 	    +- edu.stanford.cs.dawn:poly_2.12:1.1-SNAPSHOT        (depends on 1.0.6)
[warn] 	    +- org.scala-lang:scala-compiler:2.12.7               (depends on 1.0.6)
[warn] 	    +- org.scalatest:scalatest_2.12:3.0.5                 (depends on 1.0.6)
[warn] Run 'evicted' to see detailed eviction warnings
[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* org.scala-lang.modules:scala-xml_2.12:1.1.0 is selected over 1.0.6
[warn] 	    +- edu.stanford.cs.dawn:forge_2.12:1.1-SNAPSHOT       (depends on 1.0.6)
[warn] 	    +- edu.stanford.cs.dawn:utils_2.12:1.1-SNAPSHOT       (depends on 1.0.6)
[warn] 	    +- org.scala-lang:scala-compiler:2.12.7               (depends on 1.0.6)
[warn] 	    +- org.scalatest:scalatest_2.12:3.0.5                 (depends on 1.0.6)
[warn] Run 'evicted' to see detailed eviction warnings
[info] Updating argon...
[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* org.scala-lang.modules:scala-xml_2.12:1.1.0 is selected over 1.0.6
[warn] 	    +- edu.stanford.cs.dawn:forge_2.12:1.1-SNAPSHOT       (depends on 1.1.0)
[warn] 	    +- edu.stanford.cs.dawn:emul_2.12:1.1-SNAPSHOT        (depends on 1.1.0)
[warn] 	    +- edu.stanford.cs.dawn:utils_2.12:1.1-SNAPSHOT       (depends on 1.0.6)
[warn] 	    +- edu.stanford.cs.dawn:argon_2.12:1.1-SNAPSHOT       (depends on 1.0.6)
[warn] 	    +- org.scala-lang:scala-compiler:2.12.7               (depends on 1.0.6)
[warn] 	    +- org.scalatest:scalatest_2.12:3.0.5                 (depends on 1.0.6)
[warn] Run 'evicted' to see detailed eviction warnings
[info] Updating spatial...
[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* org.scala-lang.modules:scala-xml_2.12:1.1.0 is selected over 1.0.6
[warn] 	    +- edu.stanford.cs.dawn:models_2.12:1.1-SNAPSHOT      (depends on 1.1.0)
[warn] 	    +- edu.stanford.cs.dawn:poly_2.12:1.1-SNAPSHOT        (depends on 1.1.0)
[warn] 	    +- edu.stanford.cs.dawn:argon_2.12:1.1-SNAPSHOT       (depends on 1.1.0)
[warn] 	    +- edu.stanford.cs.dawn:emul_2.12:1.1-SNAPSHOT        (depends on 1.1.0)
[warn] 	    +- edu.stanford.cs.dawn:spatial_2.12:1.1-SNAPSHOT     (depends on 1.0.6)
[warn] 	    +- edu.stanford.cs.dawn:forge_2.12:1.1-SNAPSHOT       (depends on 1.0.6)
[warn] 	    +- edu.stanford.cs.dawn:utils_2.12:1.1-SNAPSHOT       (depends on 1.0.6)
[warn] 	    +- org.scala-lang:scala-compiler:2.12.7               (depends on 1.0.6)
[warn] 	    +- org.scalatest:scalatest_2.12:3.0.5                 (depends on 1.0.6)
[warn] Run 'evicted' to see detailed eviction warnings
[info] Updating ...
[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* org.scala-lang.modules:scala-xml_2.12:1.1.0 is selected over 1.0.6
[warn] 	    +- edu.stanford.cs.dawn:models_2.12:1.1-SNAPSHOT      (depends on 1.1.0)
[warn] 	    +- edu.stanford.cs.dawn:poly_2.12:1.1-SNAPSHOT        (depends on 1.1.0)
[warn] 	    +- edu.stanford.cs.dawn:argon_2.12:1.1-SNAPSHOT       (depends on 1.1.0)
[warn] 	    +- edu.stanford.cs.dawn:emul_2.12:1.1-SNAPSHOT        (depends on 1.1.0)
[warn] 	    +- edu.stanford.cs.dawn:spatial_2.12:1.1-SNAPSHOT     (depends on 1.0.6)
[warn] 	    +- edu.stanford.cs.dawn:forge_2.12:1.1-SNAPSHOT       (depends on 1.0.6)
[warn] 	    +- edu.stanford.cs.dawn:utils_2.12:1.1-SNAPSHOT       (depends on 1.0.6)
[warn] 	    +- org.scala-lang:scala-compiler:2.12.7               (depends on 1.0.6)
[warn] 	    +- org.scalatest:scalatest_2.12:3.0.5                 (depends on 1.0.6)
[warn] 	    +- edu.stanford.cs.dawn:apps_2.12:1.1-SNAPSHOT        (depends on 1.0.6)
[warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 22 Scala sources to /home/cristinazn/Downloads/tslab/spatial-master/forge/target/scala-2.12/classes ...
[info] Compiling 8 Scala sources to /home/cristinazn/Downloads/tslab/spatial-master/poly/target/scala-2.12/classes ...
[info] Compiling 13 Scala sources to /home/cristinazn/Downloads/tslab/spatial-master/models/target/scala-2.12/classes ...
[warn] While parsing annotations in /home/cristinazn/.ivy2/cache/org.jpmml/pmml-model/jars/pmml-model-1.4.10.jar(org/dmg/pmml/MiningField.class), could not find ANY in enum <none>.
[warn] This is likely due to an implementation restriction: an annotation argument cannot refer to a member of the annotated class (scala/bug#7014).
[warn] While parsing annotations in /home/cristinazn/.ivy2/cache/org.jpmml/pmml-model/jars/pmml-model-1.4.10.jar(org/dmg/pmml/MiningField.class), could not find NONE in enum <none>.
[warn] This is likely due to an implementation restriction: an annotation argument cannot refer to a member of the annotated class (scala/bug#7014).
[warn] While parsing annotations in /home/cristinazn/.ivy2/cache/org.jpmml/pmml-model/jars/pmml-model-1.4.10.jar(org/dmg/pmml/MiningField.class), could not find NONE in enum <none>.
[warn] This is likely due to an implementation restriction: an annotation argument cannot refer to a member of the annotated class (scala/bug#7014).
[warn] While parsing annotations in /home/cristinazn/.ivy2/cache/org.jpmml/pmml-model/jars/pmml-model-1.4.10.jar(org/dmg/pmml/MiningField.class), could not find NONE in enum <none>.
[warn] This is likely due to an implementation restriction: an annotation argument cannot refer to a member of the annotated class (scala/bug#7014).
[warn] While parsing annotations in /home/cristinazn/.ivy2/cache/org.jpmml/pmml-model/jars/pmml-model-1.4.10.jar(org/dmg/pmml/MiningField.class), could not find NON_EMPTY in enum <none>.
[warn] This is likely due to an implementation restriction: an annotation argument cannot refer to a member of the annotated class (scala/bug#7014).
[warn] While parsing annotations in /home/cristinazn/.ivy2/cache/org.jpmml/pmml-model/jars/pmml-model-1.4.10.jar(org/dmg/pmml/FieldName.class), could not find ANY in enum <none>.
[warn] This is likely due to an implementation restriction: an annotation argument cannot refer to a member of the annotated class (scala/bug#7014).
[warn] While parsing annotations in /home/cristinazn/.ivy2/cache/org.jpmml/pmml-model/jars/pmml-model-1.4.10.jar(org/dmg/pmml/FieldName.class), could not find NONE in enum <none>.
[warn] This is likely due to an implementation restriction: an annotation argument cannot refer to a member of the annotated class (scala/bug#7014).
[warn] While parsing annotations in /home/cristinazn/.ivy2/cache/org.jpmml/pmml-model/jars/pmml-model-1.4.10.jar(org/dmg/pmml/FieldName.class), could not find NONE in enum <none>.
[warn] This is likely due to an implementation restriction: an annotation argument cannot refer to a member of the annotated class (scala/bug#7014).
[warn] While parsing annotations in /home/cristinazn/.ivy2/cache/org.jpmml/pmml-model/jars/pmml-model-1.4.10.jar(org/dmg/pmml/FieldName.class), could not find NONE in enum <none>.
[warn] This is likely due to an implementation restriction: an annotation argument cannot refer to a member of the annotated class (scala/bug#7014).
[info] Done compiling.
[warn] 9 warnings found
[info] Done compiling.
[info] Done compiling.
[info] Compiling 93 Scala sources to /home/cristinazn/Downloads/tslab/spatial-master/argon/target/scala-2.12/classes ...
[info] Done compiling.
[info] Compiling 364 Scala sources to /home/cristinazn/Downloads/tslab/spatial-master/target/scala-2.12/classes ...
[warn] /home/cristinazn/Downloads/tslab/spatial-master/src/spatial/codegen/roguegen/RogueGenInterface.scala:35:47: non-variable type argument spatial.lang.AxiStream512 in type spatial.lang.StreamOut[spatial.lang.AxiStream512] is unchecked since it is eliminated by erasure
[warn]       if (lhs.interfaceStream.get.isInstanceOf[StreamOut[AxiStream512]]) emit(src"$lhs = base.frameOut")
[warn]                                               ^
[warn] one warning found
[info] Done compiling.
[info] Compiling 1 Scala source to /home/cristinazn/Downloads/tslab/spatial-master/apps/target/scala-2.12/classes ...
[info] Done compiling.
[success] Total time: 327 s, completed Nov 13, 2019 4:55:20 PM
[info] Loading global plugins from /home/cristinazn/.sbt/1.0/plugins
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /home/cristinazn/Downloads/tslab/spatial-master/project
[info] Loading settings from build.sbt ...
[info] Set current project to spatial (in build file:/home/cristinazn/Downloads/tslab/spatial-master/)
[info] Set current project to test (in build file:/home/cristinazn/Downloads/tslab/spatial-master/)
[info] Updating ...
[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* org.scala-lang.modules:scala-xml_2.12:1.1.0 is selected over 1.0.6
[warn] 	    +- edu.stanford.cs.dawn:models_2.12:1.1-SNAPSHOT      (depends on 1.1.0)
[warn] 	    +- edu.stanford.cs.dawn:poly_2.12:1.1-SNAPSHOT        (depends on 1.1.0)
[warn] 	    +- edu.stanford.cs.dawn:argon_2.12:1.1-SNAPSHOT       (depends on 1.1.0)
[warn] 	    +- edu.stanford.cs.dawn:emul_2.12:1.1-SNAPSHOT        (depends on 1.1.0)
[warn] 	    +- edu.stanford.cs.dawn:spatial_2.12:1.1-SNAPSHOT     (depends on 1.0.6)
[warn] 	    +- edu.stanford.cs.dawn:test_2.12:1.1-SNAPSHOT        (depends on 1.0.6)
[warn] 	    +- edu.stanford.cs.dawn:forge_2.12:1.1-SNAPSHOT       (depends on 1.0.6)
[warn] 	    +- edu.stanford.cs.dawn:utils_2.12:1.1-SNAPSHOT       (depends on 1.0.6)
[warn] 	    +- org.scala-lang:scala-compiler:2.12.7               (depends on 1.0.6)
[warn] 	    +- org.scalatest:scalatest_2.12:3.0.5                 (depends on 1.0.6)
[warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 265 Scala sources to /home/cristinazn/Downloads/tslab/spatial-master/test/target/scala-2.12/test-classes ...
[info] /home/cristinazn/Downloads/tslab/spatial-master/test/spatial/tests/feature/math/FixBasics2.scala:69:9: Type annotation recommended for var declaration.
[info]     var allgood = true
[info]         ^
[info] /home/cristinazn/Downloads/tslab/spatial-master/test/spatial/tests/feature/math/FloatBasics2.scala:70:9: Type annotation recommended for var declaration.
[info]     var allgood = true
[info]         ^
[warn] /home/cristinazn/Downloads/tslab/spatial-master/test/spatial/tests/feature/streaming/FilterStream1D.scala:49:97: postfix operator !! should be enabled
[warn] by making the implicit value scala.language.postfixOps visible.
[warn] This can be achieved by adding the import clause 'import scala.language.postfixOps'
[warn] or by setting the compiler option -language:postfixOps.
[warn] See the Scaladoc for value scala.language.postfixOps for a discussion
[warn] why the feature should be explicitly enabled.
[warn]     val filename = "cat ../src/findedges.py | grep \"calibfile =\" | sed \"s/calibfile = //g\"" !!
[warn]                                                                                                 ^
[warn] /home/cristinazn/Downloads/tslab/spatial-master/test/spatial/tests/feature/streaming/FilterStream1D.scala:52:35: postfix operator ! should be enabled
[warn] by making the implicit value scala.language.postfixOps visible.
[warn]     "python3 ../src/findedges.py" !
[warn]                                   ^
[warn] /home/cristinazn/Downloads/tslab/spatial-master/test/spatial/tests/feature/streaming/FilterStream1D.scala:57:43: postfix operator ! should be enabled
[warn] by making the implicit value scala.language.postfixOps visible.
[warn]     s"echo EXAMPLE SCALA METAPROGRAMMING" !
[warn]                                           ^
[error] ## Exception when compiling 265 sources to /home/cristinazn/Downloads/tslab/spatial-master/test/target/scala-2.12/test-classes
[error] GC overhead limit exceeded
[error] scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:111)
[error] scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:773)
[error] scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:711)
[error] scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:111)
[error] scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:773)
[error] scala.reflect.internal.Types$Type.subst(Types.scala:737)
[error] scala.reflect.internal.Types$Type.instantiateTypeParams(Types.scala:484)
[error] scala.reflect.internal.Types$TypeRef.seenFromOwnerInstantiated$1(Types.scala:2206)
[error] scala.reflect.internal.Types$TypeRef.relativize(Types.scala:2210)
[error] scala.reflect.internal.Types$TypeRef.$anonfun$baseTypeSeqImpl$2(Types.scala:2312)
[error] scala.reflect.internal.Types$TypeRef$$Lambda$3761/308046723.apply(Unknown Source)
[error] scala.reflect.internal.BaseTypeSeqs$BaseTypeSeq.map(BaseTypeSeqs.scala:145)
[error] scala.reflect.internal.Types$TypeRef.baseTypeSeqImpl(Types.scala:2312)
[error] scala.reflect.internal.Types.defineBaseTypeSeqOfTypeRef(Types.scala:2472)
[error] scala.reflect.internal.Types.defineBaseTypeSeqOfTypeRef$(Types.scala:2463)
[error] scala.reflect.internal.SymbolTable.defineBaseTypeSeqOfTypeRef(SymbolTable.scala:18)
[error] scala.reflect.internal.Types$TypeRef.baseTypeSeq(Types.scala:2319)
[error] scala.reflect.internal.BaseTypeSeqs.$anonfun$compoundBaseTypeSeq$1(BaseTypeSeqs.scala:193)
[error] scala.reflect.internal.BaseTypeSeqs.compoundBaseTypeSeq(BaseTypeSeqs.scala:192)
[error] scala.reflect.internal.BaseTypeSeqs.compoundBaseTypeSeq$(BaseTypeSeqs.scala:180)
[error] scala.reflect.internal.SymbolTable.compoundBaseTypeSeq(SymbolTable.scala:18)
[error] scala.reflect.internal.Types.defineBaseTypeSeqOfCompoundType(Types.scala:1505)
[error] scala.reflect.internal.Types.defineBaseTypeSeqOfCompoundType$(Types.scala:1465)
[error] scala.reflect.internal.SymbolTable.defineBaseTypeSeqOfCompoundType(SymbolTable.scala:18)
[error] scala.reflect.internal.Types$CompoundType.baseTypeSeq(Types.scala:1373)
[error] scala.reflect.internal.Types$PolyType.baseTypeSeq(Types.scala:2652)
[error] scala.reflect.internal.Types$TypeRef.baseTypeSeqImpl(Types.scala:2306)
[error] scala.reflect.internal.Types.defineBaseTypeSeqOfTypeRef(Types.scala:2472)
[error] scala.reflect.internal.Types.defineBaseTypeSeqOfTypeRef$(Types.scala:2463)
[error] scala.reflect.internal.SymbolTable.defineBaseTypeSeqOfTypeRef(SymbolTable.scala:18)
[error] scala.reflect.internal.Types$TypeRef.baseTypeSeq(Types.scala:2319)
[error] scala.reflect.internal.BaseTypeSeqs.$anonfun$compoundBaseTypeSeq$1(BaseTypeSeqs.scala:193)
[error]            
[error] java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: GC overhead limit exceeded
[error] 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[error] 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.take(ConcurrentRestrictions.scala:207)
[error] 	at sbt.Execute.next$1(Execute.scala:104)
[error] 	at sbt.Execute.processAll(Execute.scala:107)
[error] 	at sbt.Execute.runKeep(Execute.scala:84)
[error] 	at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:387)
[error] 	at sbt.EvaluateTask$.run$1(EvaluateTask.scala:386)
[error] 	at sbt.EvaluateTask$.runTask(EvaluateTask.scala:405)
[error] 	at sbt.internal.Aggregation$.$anonfun$timedRun$4(Aggregation.scala:100)
[error] 	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:331)
[error] 	at sbt.internal.Aggregation$.timedRun(Aggregation.scala:98)
[error] 	at sbt.internal.Aggregation$.runTasks(Aggregation.scala:111)
[error] 	at sbt.internal.Aggregation$.$anonfun$applyTasks$1(Aggregation.scala:68)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:130)
[error] 	at sbt.internal.Aggregation$.$anonfun$evaluatingParser$11(Aggregation.scala:220)
[error] 	at sbt.internal.Act$.$anonfun$actParser0$3(Act.scala:387)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:153)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:136)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:242)
[error] 	at sbt.State$$anon$1.process(State.scala:248)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:136)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:136)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:129)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:107)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:101)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:57)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:42)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:34)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:113)
[error] 	at sbt.xMain.run(Main.scala:76)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:111)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:119)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:20)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
[error] 	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:111)
[error] 	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:773)
[error] 	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:711)
[error] 	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:111)
[error] 	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:773)
[error] 	at scala.reflect.internal.Types$Type.subst(Types.scala:737)
[error] 	at scala.reflect.internal.Types$Type.instantiateTypeParams(Types.scala:484)
[error] 	at scala.reflect.internal.Types$TypeRef.seenFromOwnerInstantiated$1(Types.scala:2206)
[error] 	at scala.reflect.internal.Types$TypeRef.relativize(Types.scala:2210)
[error] 	at scala.reflect.internal.Types$TypeRef.$anonfun$baseTypeSeqImpl$2(Types.scala:2312)
[error] 	at scala.reflect.internal.Types$TypeRef$$Lambda$3761/308046723.apply(Unknown Source)
[error] 	at scala.reflect.internal.BaseTypeSeqs$BaseTypeSeq.map(BaseTypeSeqs.scala:145)
[error] 	at scala.reflect.internal.Types$TypeRef.baseTypeSeqImpl(Types.scala:2312)
[error] 	at scala.reflect.internal.Types.defineBaseTypeSeqOfTypeRef(Types.scala:2472)
[error] 	at scala.reflect.internal.Types.defineBaseTypeSeqOfTypeRef$(Types.scala:2463)
[error] 	at scala.reflect.internal.SymbolTable.defineBaseTypeSeqOfTypeRef(SymbolTable.scala:18)
[error] 	at scala.reflect.internal.Types$TypeRef.baseTypeSeq(Types.scala:2319)
[error] 	at scala.reflect.internal.BaseTypeSeqs.$anonfun$compoundBaseTypeSeq$1(BaseTypeSeqs.scala:193)
[error] 	at scala.reflect.internal.BaseTypeSeqs.compoundBaseTypeSeq(BaseTypeSeqs.scala:192)
[error] 	at scala.reflect.internal.BaseTypeSeqs.compoundBaseTypeSeq$(BaseTypeSeqs.scala:180)
[error] 	at scala.reflect.internal.SymbolTable.compoundBaseTypeSeq(SymbolTable.scala:18)
[error] 	at scala.reflect.internal.Types.defineBaseTypeSeqOfCompoundType(Types.scala:1505)
[error] 	at scala.reflect.internal.Types.defineBaseTypeSeqOfCompoundType$(Types.scala:1465)
[error] 	at scala.reflect.internal.SymbolTable.defineBaseTypeSeqOfCompoundType(SymbolTable.scala:18)
[error] 	at scala.reflect.internal.Types$CompoundType.baseTypeSeq(Types.scala:1373)
[error] 	at scala.reflect.internal.Types$PolyType.baseTypeSeq(Types.scala:2652)
[error] 	at scala.reflect.internal.Types$TypeRef.baseTypeSeqImpl(Types.scala:2306)
[error] 	at scala.reflect.internal.Types.defineBaseTypeSeqOfTypeRef(Types.scala:2472)
[error] 	at scala.reflect.internal.Types.defineBaseTypeSeqOfTypeRef$(Types.scala:2463)
[error] 	at scala.reflect.internal.SymbolTable.defineBaseTypeSeqOfTypeRef(SymbolTable.scala:18)
[error] 	at scala.reflect.internal.Types$TypeRef.baseTypeSeq(Types.scala:2319)
[error] 	at scala.reflect.internal.BaseTypeSeqs.$anonfun$compoundBaseTypeSeq$1(BaseTypeSeqs.scala:193)

**Comment by mattfel1** [comment]
You should be able to fix this by increasing some of the Java options related to memory usage.  Unfortunately, Spatial has a relatively large memory footprint right now.  If you can get away with these values on your machine, can you try `export _JAVA_OPTIONS="-Xmx10g -Xss8912k -Xms4g"`?

**Comment by lznnnnn1998** [comment]
ok, it works. but it report that "cannot compiling emptiness". 

[warn] libisl appears to be missing!  Please install http://isl.gforge.inria.fr/
[bug] An exception was encountered while compiling HelloSpatial: 
[bug]   Error compiling emptiness
[bug]   java.lang.Exception: Error compiling emptiness
[bug] This is due to a compiler bug. A log file has been created at: 
[bug]   /home/cristinazn/Downloads/tslab/spatial-master/logs/HelloSpatial//HelloSpatial_exception.log
[warn] 1 warning found
[failed] Total time: 4.9560 seconds

Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-0"
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error] 	at sbt.Run$.executeTrapExit(Run.scala:124)
[error] 	at sbt.Run.run(Run.scala:77)
[error] 	at sbt.Defaults$.$anonfun$bgRunMainTask$6(Defaults.scala:1147)
[error] 	at sbt.Defaults$.$anonfun$bgRunMainTask$6$adapted(Defaults.scala:1142)
[error] 	at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:366)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at scala.util.Try$.apply(Try.scala:209)
[error] 	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:289)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (apps / Compile / runMain) Nonzero exit code: 1
[error] Total time: 48 s, completed Nov 14, 2019 6:56:05 PM
[error] Spatial compilation failed

and i tried `cd poly/resources && gcc emptiness.c` 
some files are not correctly included:

emptiness.c:6:10: fatal error: isl/vec.h: No such file or directory
 #include <isl/vec.h>
          ^~~~~~~~~~~
compilation terminated.
after `sudo apt-get instlal libgmp3-dev libisl-dev`
it reports :
gcc emptiness.c 
/tmp/ccKDTHlJ.o: In function `main':
emptiness.c:(.text+0x6b): undefined reference to 'isl_ctx_alloc'
emptiness.c:(.text+0x99): undefined reference to 'isl_basic_set_read_from_file'
emptiness.c:(.text+0xa9): undefined reference to 'isl_basic_set_plain_is_empty'
emptiness.c:(.text+0xc5): undefined reference to 'isl_basic_set_is_empty'
emptiness.c:(.text+0xeb): undefined reference to 'isl_basic_set_free'
collect2: error: ld returned 1 exit status

but successfully run `bin/spatial HelloSpatial --sim` .

**Comment by mattfel1** [comment]
After installing libisl-dev, if you go to poly/resources and try compiling with the -lisl flag included, do you still get the error about isl/vec.h missing?  `g++ emptiness.c -lisl`

If so, I'm curious why it can't find the isl headers.  If you do "\`g++ -print-prog-name=cc1plus\` -v" can you check if the isl is installed into one of those locations? For example in my installation, it finds the isl headers in `/usr/include/isl/*.h`

Maybe you can add the correct path to `CPLUS_INCLUDE_PATH` env variable?

**Comment by lznnnnn1998** [comment]
there is no errors about isl/vec.h missing any more. 

g++ emptiness.c -lisl
/resources$ g++ emptiness.c 
/tmp/ccBGj1dV.o: In function `main':
emptiness.c:(.text+0x6b): undefined reference to 'isl_ctx_alloc'
emptiness.c:(.text+0x99): undefined reference to 'isl_basic_set_read_from_file'
emptiness.c:(.text+0xa9): undefined reference to 'isl_basic_set_plain_is_empty'
emptiness.c:(.text+0xca): undefined reference to 'isl_basic_set_is_empty'
emptiness.c:(.text+0xf5): undefined reference to 'isl_basic_set_free'
collect2: error: ld returned 1 exit status
i thinks these error can be ignored, though i'm curious about why there are these undefined references.
