### ISSUE TITLE
IDEA cannot correctly give coding suggestion

### ISSUE THREAD

**Issue by lznnnnn1998** [stanford-ppl/spatial#284]
when i tried coding by myself, i think the IDEA give coding suggestion based on Scala rather than Spatial. 
For example,  it gives some "errors" like "no implicits found for parameter bits$A$0:Bits[Int]"
  val argin1 = ArgIn[Int] (...)
  val argout1 = ArgOut[Int] (...)
  val io1 = HostIO[Int](...)

**Comment by kelayamatoz** [comment]
Hi @CristinaZN , thanks for trying out Spatial. 

By saying IDEA, do you mean you are using Intellij? If so, here's a tutorial on how to develop Spatial in Intellij: https://kelayamatoz.github.io/Digital-Systems-Design-Lab/ide.html

**Comment by lznnnnn1998** [comment]
Great instruction! Many thanks~
