### ISSUE TITLE
Ignoring Sequential.Foreach Scheduling

### ISSUE THREAD

**Issue by mattfel1** [stanford-ppl/spatial#3]
This is happening in TileLoadStoreSimple.  It is ignoring the fact that `Sequential.Foreach(size by tileSize) { i =>` has the sequential annotation for the scheduling of that controller, yet the buffering analysis seems to treat it as a sequential.

**Comment by dkoeplin** [comment]
Turns out this was a duplicate of #1. Due to an ordering issue between the new @flow analyses and the setting of user metadata, all user metadata for scheduling was being ignored. Should be fixed now
