### ISSUE TITLE
Two FIFO deq's assigned to same muxPort,muxOfs

### ISSUE THREAD

**Issue by mattfel1** [stanford-ppl/spatial#30]
In MultiplexedWrites, one of the readers to `wt` seems to have no bufferPort defined but I think it should be on bufferPort 0. Assuming this were correct though, what does a broadcasting write mean?

Also in Scan_fifofull.  It has an NBuf FIFO.  One of the dequeuers is on bufferPort 0, the other has bufferPort None.  I'm not sure what this is supposed to create.  Pairwise, these readers are time multiplexed.

```
Accel{
  Pipe.Foreach{
    // deq
    // enq
  }
  // deq
}
```

**Comment by mattfel1** [comment]
Actually this seems to just be the case with any read that is from a reduction, regs and srams are the same but I erroneously used to default to bufferPort 0 in these cases so it used to accidentally work.

**Comment by dkoeplin** [comment]
The broadcasting writer here looks correct - its a write which is sequential with a double buffer. I can't remember if the correct behavior we settled on before was we should either write only to the first buffer, or write to all buffers.

**Comment by dkoeplin** [comment]
Just pushed a fix for attempting to buffer FIFOs - should have a reasonable port layout for these dequeues now.

**Comment by mattfel1** [comment]
all looks reasonable now.   `wt` in MultiplexedWrites is now a depth 3 duplicate and depth 1 duplicate with dispatches and port info that looks reasonable.  The fifo in Scan_fillfifo is now just single buffered
