### ISSUE TITLE
Buffer Depth Wrong in NamedTest

### ISSUE THREAD

**Issue by mattfel1** [stanford-ppl/spatial#31]
This may be happening in a few places, but specifically I am looking at `a_0` which has at least 2 things wrong.

1) The LCA is the accelscope so I think it should not be buffered
2) Its getting tagged as buffered with depth = 2, which even if it did have a metapipe lca, its buffer depth should be 4

**Comment by dkoeplin** [comment]
Something weird is going on here with port calculation, looking into it tonight. 

Looks like the depth is 2 because `a` is used as MemReduce result and accumulator in a couple of places, but the ports are incorrect for this even then

**Comment by dkoeplin** [comment]
Ok, this is actually a pretty interesting example. At the moment we have two relevant rules: 
- No more than one metapipe per instance
- No merging instances when at least one has "accumulating" writes (write + read in one controller) in a buffer

**Comment by dkoeplin** [comment]
Disregard previous comment about depth needing to be 2 - there's an issue in the MemReduce stage logic still which considers the read of the output of the map and the reduction two separate stages.

**Comment by dkoeplin** [comment]
Fixed. There are still 2 duplicates in this case because we don't currently allow broadcast between the two reads in the reduction of the MemReduce, but the depth is now 1 for both instances.
