### ISSUE TITLE
Match error in PIRScheduleAnalyzer

### ISSUE THREAD

**Issue by blackwings-01** [stanford-ppl/spatial#35]
I was trying to generate PIR from spatial on DotProduct. There was a matching error on PIRPrescheduler.scala line 163 on expression Reg_read(Sym(1125)).

**Comment by blackwings-01** [comment]
Also a dumb question. I was trying to generate PIR for the unit tests in test/. what's the proper way of doing that? I tried `sbt test` and `sbt test-only *.SimpleAccumMem` but those gave bunch of compilation error. I also saw --test in spatial script but `spatial --test --CGRA SimpleAccumMem` also doesn't seems to be right. Do I need to copy the unit test to apps and run with spatial script?
@dkoeplin

**Comment by dkoeplin** [comment]
Yeah for now you need to copy them to the apps folder. I haven't gotten sbt to recognize the tests project directory yet, not sure what's wrong there. I'll look at the match error first thing tomorrow.

**Comment by blackwings-01** [comment]
@raghup17 
When you said generating unit test for PIR did you mean the tests in spatial/tests or some of the apps in spatial/apps like? It seems the tests in spatial/tests are a little bit outdated that some of them doesn't compile, or there're specific ones that we are looking at?

**Comment by raghup17** [comment]
Yeah, I was refering to the apps in CodegenUnitTests.scala. There are multiple apps defined within that single file. We can ignore InsanityTests.scala for now.

**Comment by dkoeplin** [comment]
Turned out it was just a small issue carried over from the memory analysis change that I hadn't found yet. Fixed and pushed to transform and pirgen branches.
