### ISSUE TITLE
AccelScope with Nothing Inside is Still OuterControl

### ISSUE THREAD

**Issue by mattfel1** [stanford-ppl/spatial#4]
Should this be the case?  All of the apps that have nothing in the accel, like the host tests, have this problem probably.

**Comment by dkoeplin** [comment]
I think this issue should be fixed now? For some reason I put in a special case for Accel that we didn't actually want.

**Comment by dkoeplin** [comment]
Should be fixed as of f6d74d383d583a83b031ed1677223017626a9e6d
