### ISSUE TITLE
Use addrWidth instead of dataWidth in AWS Top

### ISSUE THREAD

**Issue by dkoeplin** [stanford-ppl/spatial#40]
nova/resource/synth/Top.scala

dataWidth should be addrWidth in AWS interface on line 137/138

**Comment by mattfel1** [comment]
@shadjis  Is there some obscure reason for this or is it safe to make it 
val axiLiteParams = new AXI4BundleParameters(~~p.dataWidth~~ p.addrWidth, p.dataWidth, 1)?

**Comment by cs217** [comment]
I don't know of any reason but I don't recognize this code so maybe Raghu wrote it

**Comment by shadjis** [comment]
I don't know of any reason but I don't recognize this code so maybe Raghu wrote it

**Comment by mattfel1** [comment]
I'll change it. Hopefully we don't notice new failures on aws

**Comment by shadjis** [comment]
Why not test it first then

**Comment by mattfel1** [comment]
I'm checking matmult now but the aws process is so slow and painful so its possible this one will work but another one won't

**Comment by shadjis** [comment]
ok
was this also an issue for line 138? Maybe both lines were supposed to change?
