### ISSUE TITLE
Kmeans memory not duplicated

### ISSUE THREAD

**Issue by mattfel1** [stanford-ppl/spatial#44]
Not sure if this is a bug or an app mistake.

In Kmeans, I have an outerloop that loads in `pts`.  I then have a fold which has two different stages that both read from `pts`.  If I set the outer parallelization of the fold to 2, I would expect `pts` to have 4 duplicates, since there are two places where it is read and these get duplicated x2.  There are only 2 duplicates though and both are reading from it.  Is this correct?  It crashes right now in MaxJ because I can't connect two sets of addresses to `pts` unless if I know the addresses will always be the same.

**Comment by dkoeplin** [comment]
Fixed in most recent commit. Duplication of each instance also has to be checked, per our discussion yesterday.
