### ISSUE TITLE
Grouping Reads Separately when they May Fire Together

### ISSUE THREAD

**Issue by mattfel1** [stanford-ppl/spatial#49]
From FFT_Strided:

```
        Foreach(8 by 1) { i => 
          Pipe{tmem_x(reversed_LUT(i)) = work_x_sram(i, tid)}
          Pipe{tmem_y(reversed_LUT(i)) = work_y_sram(i, tid)}
        }
```

Both reads to `reversed_LUT` can happen at the same time, but they get grouped separately and therefore sit on different muxPorts that fire together.  I think either memory templates need to change since they can't safely use the wides muxPort to set the number of data wires or these need to get grouped together

**Comment by dkoeplin** [comment]
Should be fixed from the merged pull request - problems with the fix should have a new issue.
