### ISSUE TITLE
Random Broadcast Write Appearing

### ISSUE THREAD

**Issue by mattfel1** [stanford-ppl/spatial#5]
In FixBasics2, the writer that does ` ff_out_sram(1, i) = sram1(i) * sram2(i) ` is a `- class spatial.data.Ports: Ports(Map(List(0) -> Port(0,None)))`.  All of the other writers have their bufferPort set correctly except this one.

**Comment by dkoeplin** [comment]
Should be fixed. Granted, this shouldn't be buffered at all.. but that's a separate bug
