### ISSUE TITLE
Smarter Banking Search

### ISSUE THREAD

**Issue by mattfel1** [stanford-ppl/spatial#60]
For something like:

```
val x = SRAM[Int](96,3,3,96)
Foreach(96 par 2){r => 
  Foreach(96) { c =>
    x(r,0,0,c)
    x(r,0,1,c)
    ...
    x(r,2,1,c)
    x(r,2,2,c)
  }
}
```
It is trying every possible power of 2 alpha combination and then the non power of 2 alphas, but visually inspecting this I think it should be relatively easy to jump straight to something like alpha=<9,3,1,0>.

Also there is no point in having AlphasX or Alphas2 contain two numbers if they are equal mod N

**Comment by mattfel1** [comment]
I thought about this a bit and I have a solution that works much faster for at least some of our banking-intensive apps.  Here is the new `Alphas` in exhaustive banking.

The idea is searching all powers of 2 first, then brute forcing all numbers next takes forever to hit on a valid scheme.  I think in the common case, the alphas will be either a power of 2, some factor of N, or a number that is a product of a subset of the dimensions (ex a 10x3x3 matrix has banks 0-8 on page 0, 9-17 on page 1, etc).  I added the AlphasLikely set to try searching through these first.
```
  /**
    * Generates an iterator over all vectors of given rank, with values up to N
    * Prioritizes vectors which are entirely powers of 2 first
    * Next prioritizes vectors composed of either 
    *    1) Number that evenly divides N
    *    2) Number that is the result of a product of some combination of stagedDims (Not sure if this increases the likelihood of valid schemes compared to option 1 only)
    *    3) Number that is also power of 2
    *    (consider something like 96x3x3x96 sram N = 36, want to try things like alpha = 18,1,3,9)
    * Note that the total size is O(N**rank)
    */
  def Alphas(rank: Int, N: Int, stagedDims: Seq[Int]): Iterator[Seq[Int]] = {
    // Prime factors of number, for shortcircuiting the brute force alphas
    def factorize(number: Int, list: List[Int] = List()): List[Int] = {
      for(n <- 2 to number if (number % n == 0)) {
        return factorize(number / n, list :+ n)
      }
      list
    }

    val a2 = (0 to 2*N).filter(x => isPow2(x) || x == 1 || x == 0)
    val alikely = (
                Seq(0,1) ++ 
                Seq.tabulate(factorize(N).length){i => factorize(N).combinations(i+1).toList}.flatten.map(_.product) ++ 
                Seq.tabulate(stagedDims.length){i => stagedDims.combinations(i+1).toList}.flatten.map(_.product).filter(_ <= N) ++ 
                (0 to 2*N).filter(isPow2(_))
               )
    def Alphas2(dim: Int, prev: Seq[Int]): Iterator[Seq[Int]] = {
      if (dim < rank) {
        a2.iterator.flatMap{aD => Alphas2(dim+1, prev :+ aD) }
      }
      else a2.iterator.map{aR => prev :+ aR }
    }
    def AlphasLikely(dim: Int, prev: Seq[Int]): Iterator[Seq[Int]] = {
      if (dim < rank) {
        alikely.iterator.flatMap{aD => AlphasLikely(dim+1, prev :+ aD) }
      }
      else alikely.iterator.map{aR => prev :+ aR}
    }
    def AlphasX(dim: Int, prev: Seq[Int]): Iterator[Seq[Int]] = {
      if (dim < rank) {
        (0 to 2*N).iterator.flatMap{aD => AlphasX(dim+1, prev :+ aD) }
      }
      else (0 to 2*N).iterator.map{aR => prev :+ aR }.filterNot(_.forall(x => isPow2(x) || x == 1))
    }
    Alphas2(1, Nil).filterNot(_.forall(_ == 0)) ++ AlphasLikely(1, Nil).filterNot{x => x.forall(_ == 0) || x.forall(isPow2(_))} ++ AlphasX(1, Nil).filterNot(_.forall(_ == 0))
  }

```

A driving case was a 96x3x3x96 memory, where we access dims 0 and 3 with par 2 and all 9 elements along dims 1 and 2 in parallel.  The obvious human solution would be to set alpha=18,1,3,9.  These alphas would eventually hit this, but they get to alpha=1,2,6,18 first which is also technically correct but a little more confusing.  I think playing around with the ordering of `alikely` and how the alphas get assembled should change this but I don't think it matters

**Comment by mattfel1** [comment]
Added uniqueModN on Seq implicits to get rid of alpha value collisions mod N

**Comment by dkoeplin** [comment]
Good idea - I was meaning to get around to this improvement!
