### ISSUE TITLE
Flow Setting Controller as Sequential Before Unit Pipe Insertion

### ISSUE THREAD

**Issue by mattfel1** [stanford-ppl/spatial#68]
For example:

```
'PROBLEM.Foreach(N by 1){ i =>
  Foreach(...){...}
  sram(i) = ...
}
```
When this gets staged, `PROBLEM` only has one child and therefore its schedule is set to be sequential, even though the sram write will eventually be put in a unit pipe and then it will contain two stages that should be scheduled in a pipeline

**Comment by dkoeplin** [comment]
Ah, good call. The analysis should also check if there are any primitive operations directly under that controller that will become other stages.

**Comment by dkoeplin** [comment]
Assigned to myself but if you get to it before I do, should be an easy fix

**Comment by mattfel1** [comment]
I thought it may be expensive to check every statement in every flow so I
made another case locally where I convert sequenced to pipelined if there
are more than one child, it’s an outer pipe and has no user schedule. This
eventually catches the case in unrolling I think. Maybe it’s a dangerous
assumption but I couldn’t think of any example this would be wrong, unless if DSE is changing raw schedule and should not be overriden. Should I just redo it to
use your method?  You can take a look at it on issue61 branch.

**Comment by dkoeplin** [comment]
My only (minor) concern there is we may eventually have passes which try to downgrade the schedule from Pipeline to Sequential (e.g. for cost reasons). This flow would override those analyses. Besides that it seems reasonable though.
