### ISSUE TITLE
muxSize in Port is incorrect and unused

### ISSUE THREAD

**Issue by dkoeplin** [stanford-ppl/spatial#92]
Not sure if this is eventually needed in code generation, but the muxSize field in Port is currently unused in code generation and analyses, and is incorrect in cases where broadcast is used. If you're ok with it @mattfel1, we can just remove this field. It can always be recalculated based on vector widths and the muxOfs field.

**Comment by mattfel1** [comment]
Could be used in cg to make it simpler, but things are working fine without it so probably not worth fixing

**Comment by dkoeplin** [comment]
We'll just remove that field for now. We can have a helper method for codegen which calculates the same thing, but correctly.
