### ISSUE TITLE
Double Connections To Port for RegRead

### ISSUE THREAD

**Issue by mattfel1** [stanford-ppl/spatial#94]
Looking at ReduceArbitraryLambda:

```
x147 = RegRead(x132)
 - class spatial.metadata.memory.Ports: Ports(Map(0 -> Map(List() -> Port(Some(0),0,2,0,List(0),List(0)))))
x148 = RegRead(x132)
 - class spatial.metadata.memory.Ports: Ports(Map(0 -> Map(List() -> Port(Some(0),0,2,0,List(0),List(0)))))
```
x132 is `fold_xor_0`

Illegal connection?

**Comment by dkoeplin** [comment]
Requires explicit CSE of register reads. We had it in the prior version of spatial, somehow that hadn't made it into the new version yet. Now added on the broadcast branch
